# Generated by Django 5.1.4 on 2025-01-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='date_first_appt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
