# Generated by Django 5.1.4 on 2025-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0002_alter_useraccounts_date_first_appt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
