# Generated by Django 5.1.4 on 2025-01-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0003_alter_useraccounts_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
