# Generated by Django 5.1.4 on 2025-05-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0004_alter_useraccounts_email'),
        ('core', '0002_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userdept', to='core.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userunits', to='core.unit'),
            preserve_default=False,
        ),
    ]
