# Generated by Django 5.1.4 on 2025-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0005_useraccounts_dept_useraccounts_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='address',
            field=models.TextField(blank=True, help_text='Current residential address', null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Blood group of the employee', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact person', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='grade_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='id_card_mumber',
            field=models.CharField(blank=True, help_text='Unique employee identification number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='ippis_number',
            field=models.CharField(blank=True, help_text='Integrated Personnel and Payroll Information System number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='local_government',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='open_number',
            field=models.CharField(blank=True, help_text='Open number for employee identification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='secret_number',
            field=models.CharField(blank=True, help_text='Secret number for employee identification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
