# Generated by Django 5.1.4 on 2025-06-11 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0006_useraccounts_address_useraccounts_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.BooleanField(help_text='Previous active status of the account')),
                ('new_status', models.BooleanField(help_text='New active status of the account')),
                ('status_change', models.CharField(choices=[('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated')], editable=False, help_text='Type of status change', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the status change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(help_text='User who made the status change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_status_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_status_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Status History',
                'verbose_name_plural': 'Account Status Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='UserAccount_user_id_e4dcdc_idx'), models.Index(fields=['status_change'], name='UserAccount_status__0344d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], default='desktop', max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('os_type', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('login_date', models.DateField(auto_now_add=True)),
                ('login_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='success', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_desktop', models.BooleanField(default=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_secure', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'login_time'], name='UserAccount_user_id_3a95d7_idx'), models.Index(fields=['login_status'], name='UserAccount_login_s_69ef85_idx'), models.Index(fields=['device_type'], name='UserAccount_device__c821c0_idx')],
            },
        ),
    ]
