# Generated by Django 5.1.4 on 2025-06-11 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0007_accountstatushistory_loginhistory'),
        ('core', '0003_remove_leaverequest_deductible_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdept', to='core.department'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userunits', to='core.unit'),
        ),
    ]
